### ISSUE TITLE
[noob] what does "no go-ipfs compatibility" mean?

### ISSUE THREAD

**Issue by akavel** [ipfs-rust/ipfs-embed#101]
In the readme, I noticed the following disclaimer:

> It does not aim at being compatible in any way with `go-ipfs`.

Could I kindly ask if you would fancy trying to help me understand what does this mean, for an IPFS noob? Most notably, does it mean:
 - (a) that files shared on IPFS by go-ipfs or js-ipfs are not visible/gettable from ipfs-embed, and reverse? (i.e. they are completely "separate ecosystems/networks")
 - (b) or, that the files *are* cross-visible, but just the "local on-disk database and contents of downloaded/shared files" is not compatible? i.e. in other words, they are "network compatible", but ipfs-embed is just not (and will not be) a drop-in replacement for go-ipfs and reverse?

TIA! ❤️ 

(*edit:* In my particular case, I'm interested in writing a small personal-use app for sharing photos over IPFS - more or less trying to rewrite https://github.com/akavel/catation in Rust - and wonder if that's currently something I could manage to achieve in Rust somehow)

**Comment by dvc94ch** [comment]
You can configure ipfs-embed to work with go-ipfs, by setting the bootstrap nodes and using the unixfs crate and writing a little bit of code to hook it all up. Ipfs-embed  works at a lower level of abstraction, suitable for embedding into different kinds of applications

**Comment by RangerMauve** [comment]
> You can configure ipfs-embed to work with go-ipfs, by setting the bootstrap nodes and using the unixfs crate and writing a little bit of code to hook it all up. Ipfs-embed works at a lower level of abstraction, suitable for embedding into different kinds of applications

Is there an example repo somewhere of this working? Go-ipfs compatibility seems like a common requirement, and it'd be nice to be able to reuse something proven to work. 😁

**Comment by dvc94ch** [comment]
> Could I kindly ask if you would fancy trying to help me understand what does this mean, for an IPFS noob?

Well the intention behind it is don't spam my issue tracker, but since that doesn't work... You can enable dag-protobuf in libipld for the second error. For the first error make sure you pin the block.

**Comment by elmattic** [comment]
@dvc94ch many thanks, it worked with the dag-pb feature. The first error disappeared at the same time (without pinning).

**Comment by rkuhn** [comment]
This looks like it was resolved.
