### ISSUE TITLE
support for gossipsub

### ISSUE THREAD

**Issue by scanlime** [ipfs-rust/ipfs-embed#18]
Is any support for publish/subscribe planned? At the moment it looks like this wouldn't be possible without forking the crate.

**Comment by dvc94ch** [comment]
I'll be adding a network trait soon that will allow you to do your own networking. Does that help? Pubsub is not really required for ipfs, so it's not enabled.

**Comment by dvc94ch** [comment]
Added network trait, closing.

**Comment by dvc94ch** [comment]
I changed my mind on this feature. It only requires providing two additional functions `publish` and `subscribe`, I think we can have them in ipfs-embed.

**Comment by cryptoquick** [comment]
That'd be perfect, @dvc94ch, since I do have pub/sub planned, but it's also nice that you expose the network traits. I assume that allows us to hook into libp2p and, say, allow nodes to communicate with other nodes directly?

**Comment by dvc94ch** [comment]
Opened a wip pr for this here #32. If someone is interested in finishing it, it needs at least one passing test. I'm not too bothered about it right now

**Comment by dvc94ch** [comment]
Closed by #31
