### ISSUE TITLE
remove async-std dependency

### ISSUE THREAD

**Issue by dvc94ch** [ipfs-rust/ipfs-embed#26]
waiting on interval api in async-io and a solution for task spawning

**Comment by cryptoquick** [comment]
FYI, I'm currently using this with [https://github.com/hecrj/iced](iced), which has a feature flag for async-std.

pretty pls do not break my code with your new code pls tyvm

**Comment by dvc94ch** [comment]
ipfs-embed will use the `async-global-executor` and `async-io`. Fixed in #31

**Comment by cryptoquick** [comment]
Ah, makes sense. I incorrectly inferred you were moving to tokio.

**Comment by dvc94ch** [comment]
Closed by #31
