### ISSUE TITLE
rewrite sled block store

### ISSUE THREAD

**Issue by dvc94ch** [ipfs-rust/ipfs-embed#33]
the ipfs-sqlite-block-store supports features like `reverse_alias`, `missing_blocks`, `tmp_pin`, `stats`, supports O(1) aliasing and has an incremental garbage collector. the current `ipfs-embed-db` needs to be redesigned to support these features.

for debugability the block store needs to be able to support dumping a snapshot and starting with an in memory copy of a snapshot

**Comment by cryptoquick** [comment]
Ah, I see. I support this. Best to cover lots of ground quickly, rather than "the perfect being the enemy of the good."

**Comment by dvc94ch** [comment]
I'm probably not going to work on this as the ipfs-sqlite-block-store works well enough
