### ISSUE TITLE
Could this Support Web?

### ISSUE THREAD

**Issue by zicklag** [ipfs-rust/ipfs-embed#34]
Hey there, this is a very interesting project! I was wondering whether or not it was possible to make this work in the browser with WASM. Are there traits that could be used to abstract the storage and networking components so that we could make browser-compatible implementations? Are there any other issue that we might run into?

I'm mostly curious and not sure if I'd end up using it for anything serious, but was wondering how that might work.

**Comment by dvc94ch** [comment]
No, the web is not a suitable platform. If you want to use ipfs in the web just use a gateway.

**Comment by zicklag** [comment]
OK, thanks.
