### ISSUE TITLE
porting to support libp2p-rs 

### ISSUE THREAD

**Issue by kingwel-xie** [ipfs-rust/ipfs-embed#35]
Hi,

We are the owners of libp2p-rs, which is an alternative of rust-libp2p. Recently, we released the v0.2.0, which might be a good start for building some real stuff, even it is far away from mature.

So, are you guys interesting in it? I believe it is quite promising to port your code to libp2p-rs using async/await to write code. Please let me know what you think.

Thanks,
Kingwel

**Comment by cryptoquick** [comment]
We've certainly been keeping an eye on it. I'm not a maintainer, but we've chatted about this in our Element channel, `#rust-ipfs:matrix.org`. I'd certainly be interested in using a version of ipfs-embed that used libp2p-rs.

**Comment by dvc94ch** [comment]
Very interested yes, although there are other priorities at the moment. Having the relay and/or quic would help "prioritize" as those are large features that have stalled in rust-libp2p for a long time.

**Comment by kingwel-xie** [comment]
Sound great! We'll look into your code at first to figure out what to do next. Hopefully we can come back with some suggestions in a few days.

BTW, it should be mentioned that libp2p-rs is quite different from rust-libp2p, which we believe is too complicated in way (too many generic types and code written in the poll method).  Therefore we re-wrote Swarm/Protocols to use async/.await completely...

**Comment by kingwel-xie** [comment]
Sorry for the late update. We finally choose to start with rust-ipfs after comparing ipfs-embed with it. Simply because we think rust-ipfs has more features and better interoperability with go-ipfs. 

We'll fork rust-ipfs and start the code porting as soon as we come back from Lunar new year holiday. It is really appreciated that you could work together with us on the porting.

**Comment by dvc94ch** [comment]
You missunderstand what the intent is of ipfs-embed. It is close to "complete", no new features will be added once https://github.com/ipfs-rust/ipfs-embed/pull/31 is merged. Ipfs-embed was built to be small, fast and reliable.

**Comment by dvc94ch** [comment]
So I added a disclaimer in the `README` that explicitly states that it does not intend to be compatible with `go-ipfs`. At `actyx` and before that at `sunshine` we found that `go-ipfs` or `rust-ipfs` does not fit our requirements. Since we don't use ipfs as a cache for a webserver and we need reliability and support for dynamically changing data, we had to build our own ipfs implementation.

**Comment by dvc94ch** [comment]
Closing for now, feel free to reopen if you add support for nat traversal or quic. At the moment ipfs-embed relies heavily on rust-libp2p and would probably have to be largely rewritten. Also we use the rust-libp2p request-response protocol, which I don't think you support yet.

**Comment by kingwel-xie** [comment]
We are close to finish porting [rust-ipfs](https://github.com/rs-ipfs/rust-ipfs) to libp2prs. The reason was explained above. But we are thinking if we can do that for ipfs-embed as well, since we could reuse the thoughts completely. As we can see, based on libp2prs would make your code much simpler, and easy to maintain.

Anyway, we'd make a fork and finish porting in a few days. Will keep you posted.

**Comment by kingwel-xie** [comment]
Almost done. See [code](https://github.com/kingwel-xie/ipfs-embed). At least it woks with the examples/simple...

Some points:

1. as mentioned before, we mainly focused on rust-ipfs which we believe has more features. Therefore, the porting on ipfs-embed is something like a proof that libp2prs can work with yet another application.
2. ipfs::sync() is not implemented. We might have to implement a new API of fetch_many_blocks which returns a Stream...
3. bitswap in ipfs-embed is quite unique in a way. Eventually I decided to replace it with the bitswap code ported for rust-ipfs, which is compatible with the go-bitswap implemntation
4. mdns is not done yet. Shouldn't be a big deal, but mdns in libp2prs was never tested thoroughly
5. a CLI is added to better debugging/testing the code. key in 'help'/'h' will get some prompts. We do have some CLI commands for swarm and kad, and two commands are added for ipfs block get/put
6. there is something wrong with the ipld/block codec. As a result, blocks created by go-ipfs can NOT be recognized by ipfs-embed. It looks like dagPb is not enabled. However, I got a prost decodeError if enabling it...
7. test code should work in most cases, I suppose. Honestly I didn't spend much time on it.
8. unfortunately the APIs provided by libp2prs is completely different from rust-libp2p, consequently we have to refactor the code of ipfs-embed. The good news is libp2prs is much simpler, thus ipfs-embed using libp2prs is simpler as well. Swarm and its protocols are manipulated by the controllers, and all controllers construct the network service used by ipfs-embed. See code for the details.

any comments are appreciated!

BR/Kingwel

**Comment by dvc94ch** [comment]
I can understand your rudeness to a degree. In china the communist government tells everyone what to do. I live in a free society, which means if you don't like ipfs-embed don't use it, no need to insult the authors constantly.

You seem to be somewhat unimaginative and want a go ipfs clone in rust. In that case just use go ipfs. And you're probably unaware but I wrote rust-ipfs, so maybe I know a thing or two about how to build (and not to build) an ipfs implementation.

libp2p-rs is behind on bug fixes, rust-libp2p bug fixes/features have not been backported.

**Comment by vmx** [comment]
I find it reasonable if people from libp2prs want to give a port a try and see where it goes. The background that the Bitswap implementation is intentionally different from the ipfs-rust/rust-ipfs one might night be obvious at first sight. So the feedback would be, that the ipfs-rust/rust-ipfs Bitswap cannot be used, but the current implementation would need to be ported.

Though it's also reasonable for @dvc94ch to just say that there is no interest in switching to libp2prs and that he won't spend time to do a deeper review for in depth feedback as he still sees features/bug fixes missing.

**Comment by dvc94ch** [comment]
So I've been called out for not understanding china and making this political. But to clarify my statement and why I don't think it's missguided:

> It is polite that if you don't like something, assume that either someone does or the project will fail due to capitalistic market forces, without an authority having to decide if it's a worthy enterprise.
