### ISSUE TITLE
Derive Debug for Ipfs

### ISSUE THREAD

**Issue by rklaehn** [ipfs-rust/ipfs-embed#62]
...and for its components.

Slightly annoying to not have it.

**Comment by cryptoquick** [comment]
Heh, someone had to say it. :)

**Comment by dvc94ch** [comment]
Will be in the next release. Looks like a libp2p will take a while, but I also need to finish some of the libp2p-quic/noise details before this can be released. If I don't finish before the next libp2p release I'll add feature gates for the quic parts.
